# Generated by Django 5.1.3 on 2024-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
