# Generated by Django 4.2.6 on 2024-11-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_viewing_client_similarclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='similarclient',
            options={'ordering': ['-similarity_score']},
        ),
        migrations.AlterField(
            model_name='viewing',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.client'),
        ),
    ]
