# Generated by Django 4.2.6 on 2024-11-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_similarclient_options_alter_viewing_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
